print('номер рейса')
flight=input()
print('название авиакомпании (на русском)')
title_rus=input()
print('название авиакомпании (на английском)')
title_eng=input()
print('город прилета (на русском)')
city_rus=input()
print('город прилета (на английском)')
city_eng=input()
print('Заканчивается посадка на рейс', flight, 'авиакомпании', title_rus, 'до', city_rus)
print('This is the final boarding call for', title_eng, 'Airlines', 'flight', flight, 'to', city_eng)